### ISSUE TITLE
[BUG] 404 On Live Site

### ISSUE THREAD

**Issue by brandonapol** [ExoKomodo/Edu#132]
### What is wrong?

Courses page stuck in spinning wheel and no results

### How can I, the developer, reproduce this?

It's on the live server

### Supplemental attachments?

<img width="782" alt="Screen Shot 2023-05-26 at 3 58 39 PM" src="https://github.com/ExoKomodo/Edu/assets/72466214/76f35704-a738-4612-ae69-843dc73eb122">
<img width="1430" alt="Screen Shot 2023-05-26 at 3 58 33 PM" src="https://github.com/ExoKomodo/Edu/assets/72466214/6a2bdb20-c672-47fb-83fc-5650f2d2c138">

### Acceptance Criteria

Courses load

**Comment by JamesOrson** [comment]
Works when logged in as exokomodo@gmail.com
![image](https://github.com/ExoKomodo/Edu/assets/17893076/7af32203-28d5-470e-b119-e599a6bd0105)

How did you log in? What email was used?

**Comment by JamesOrson** [comment]
The auth0 token is pretty messed up though

Often when I first visit a page, it shows me logged in, but I am definitely not and need to logout or I get results like yours

**Comment by JamesOrson** [comment]
I can even visit with my personal email I have set as a non-admin account:
![image](https://github.com/ExoKomodo/Edu/assets/17893076/0f9714c0-7e84-4a4b-be90-e9cfed7fa1c0)

**Comment by brandonapol** [comment]
No longer seeing the issue; I suspect back end fixed it
