### ISSUE TITLE
[BUG] Styling is not readable on blog page

### ISSUE THREAD

**Issue by JamesOrson** [ExoKomodo/Edu#35]
# Description

This is literally unreadable
![image](https://user-images.githubusercontent.com/17893076/228418628-8b22292b-28ef-48be-87f8-a63be193363c.png)

# Acceptance Criteria

Make it readable

**Comment by brandonapol** [comment]
What is the back end API endpoint I'm aiming for here?

**Comment by brandonapol** [comment]
I can run this locally, but there's still nothing in the DB for me to style. There isn't (as far as I know) any data to be displayed yet, so kind of hard to style it. I am probably missing something but I'm not sure what the real bug is here

**Comment by JamesOrson** [comment]
tl;dr we talked offline and the API works but the text is black on a background of a lesser black

**Comment by JamesOrson** [comment]
Still not readable on the actual blog page

The list is fixed, but the blog content pages are unreadable

![Screen Shot 2023-04-03 at 10 46 54 AM](https://user-images.githubusercontent.com/17893076/229587277-01b15212-1787-4f5d-94a5-af693ca070e2.png)
