### ISSUE TITLE
[BUG] my bug is named CORS and I want to squish him

### ISSUE THREAD

**Issue by brandonapol** [ExoKomodo/Edu#73]
# Bug

## What is wrong?

CORS error when running locally

## How can I, the developer, reproduce this?

Made a branch off of main, ran server and client (dotnet run and npm run dev, respectively) and upon visiting the /blogs endpoint of the Vue app I am receiving CORS errors. It seems there is also a type error that is preventing the blog from rendering at all. I 'fixed' this by creating local 'dummy' data, but this is API-free data, so not really useful.

## Acceptance Criteria

Data pulls and blogs display from DB via backend
<img width="657" alt="Screen Shot 2023-04-07 at 7 59 21 PM" src="https://user-images.githubusercontent.com/72466214/230694037-00c2269a-1035-4c52-a5e0-141303c39950.png">

**Comment by brandonapol** [comment]
Added my current code as-is (with styling fixed and dummy data commented out) so you can see how I am arriving at this exactly.

**Comment by brandonapol** [comment]
At BlogView.vue:

`//! This has had a name change so that it does not get used as data
//! By commenting it out the page will run and locally useable dummy data works
// const realBlogs: Blog[] = await BlogService.getAllStubs();
// TODO: fix
const blogs = [
  {
    title: "uno",
    id: '1',
    content: "some content",
    description: "yabba dabba doo"
  }
]`

**Comment by JamesOrson** [comment]
I checked and this is because your dev branch is out of date with `main` and is missing the fix

Rebase your branch with main and you will be fine

**Comment by JamesOrson** [comment]
Your PR says you have merge conflicts which is indicative of being out of date

![C25C2E6C-7897-4666-B3D9-ABCB6C5638D0](https://user-images.githubusercontent.com/17893076/230695864-43c20155-9bf4-46e6-9721-06f9f4b210d7.png)
